export default {
  "text.accept": "Accept",
  "text.aspect-ratio": "Aspect ratio",
  "text.back": "Back",
  "text.b": "B",
  "text.bold": "Bold",
  "text.breadcrumb": "Breadcrumb",
  "text.bullets": "Bullets",
  "text.c": "C#",
  "text.camera-api-is-not-available-in-this-browser": "Camera API is not available in this browser.",
  "text.camera-permission-was-denied": "Camera permission was denied.",
  "text.captured": "Captured:",
  "text.cast": "Cast",
  "text.clear-formatting": "Clear formatting",
  "text.clear-text": "Clear text",
  "text.close": "Close",
  "text.close-overflow-menu": "Close overflow menu",
  "text.command-bar": "Command bar",
  "text.copy": "Copy",
  "text.cut": "Cut",
  "text.g": "G",
  "text.hue": "Hue",
  "text.integrated-camera": "Integrated camera",
  "text.italic": "Italic",
 回事 "text.more": "More",
  "text.more-options": "More options",
  "text.mute": "Mute",
  "text.navigation-menu": "Navigation menu",
  "text.next": "Next",
  "text.numbering": "Numbering",
  "text.off": "Off",
  "text.on": "On",
  "text.paste": "Paste",
  "text.pause": "Pause",
  "text.play": "Play",
  "text.previous": "Previous",
  "text.r": "R",
  "text.redo": "Redo",
  "text.reveal-password": "Reveal password",
  "text.scroll-left": "Scroll left",
  "text.scroll-right": "Scroll right",
  "text.select": "Select...",
  "text.select-all": "Select all",
  "text.settings": "Settings",
  "text.source-code": "Source code",
  "text.saturation": "Saturation",
  "text.submit-query": "Submit query",
  "text.switch-to-zoomed-out-view": "Switch to zoomed out view",
  "text.cancel": "Cancel",
  "text.underline": "Underline",
  "text.undo": "Undo",
  "text.unmute": "Unmute",
  "text.value": "Value",
  "text.volume": "Volume",
  "text.vue": "Vue",
  "text.xaml": "XAML"
};
